### ISSUE TITLE
Cannot resolve "webhook.ingestion.office.com"

### ISSUE THREAD

**Issue by lb-cyway-one** [microsoft/m365-compliance-connector-sample-scripts#12]
Hello,

It seems that there is an issue with DNS resolution for "webhook.ingestion.office.com". After getting the error from the script, I've investigated and can confirm that most DNS servers are not able to resolve "".

Here are the test performed:
```
/tmp %  dig +short @8.8.8.8 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
/tmp %  dig +short @1.1.1.1 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
/tmp %  dig +short @208.67.222.222 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
/tmp %  dig +short @9.9.9.9 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
/tmp %  dig +short @209.244.0.3 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
/tmp %  dig +short @216.146.35.35 webhook.ingestion.office.com
ingestion-webhook.trafficmanager.net.
prod-cnc-webhookserviceapi.canadacentral.cloudapp.azure.com.
4.205.63.95
/tmp % 
```

Out of 6 well known public DNS, only one is able to perform the full resolution. The other are stuck at the first alias: "ingestion-webhook.trafficmanager.net."

I understand that the issue is not with the script itself, but I don't know where else to raise the issue. 

Any type of support or link to the team responsible for this service would be appreciated.

Thanks.

**Comment by MScottGH** [comment]
@lb-cyway-one 

I had a similar issue, previously working Automation broke overnight.

After 90 mins with Microsoft support, between us (and using postman) we found that the URL has changed to https://webhook-ne.ingestion.office.com/api/signals.

The Automation and connector now fully working again. Looks like Microsoft need a documentation update.

**Comment by Piotr-GitHub** [comment]
The issue with "webhook.ingestion.office.com" should work now. There is no need to change the URL.
